project:
  type: website
  output-dir: docs
  title: "Tan Gandhara"

website:
  bread-crumbs: false
  sidebar:
    style: "floating"
    search: false
    contents:
      - section: "About Me"
        contents:        
        - index.qmd
      - section: "Projects"
        contents:
        - projects1.qmd
        - projects2.qmd
        - projects.qmd
      - section: "Tutorials"
        contents:  
        - guides.qmd
        - links.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/tan-gandhara
      - icon: chat-quote-fill
        href: https://bsky.app/profile/tangandhara.bsky.social
      - icon: github
        href: https://github.com/tangandhara
      - icon: envelope
        href: mailto:tangandhara+quarto@hotmail.com

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

